name: open-games-hs-preprocessor
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.m.zahn@gmail.com
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: MIT
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
    - OpenGames.Preprocessor
    - OpenGames.Preprocessor.BlockSyntax
    - OpenGames.Preprocessor.Codegen
    - OpenGames.Preprocessor.CompileBlock
    - OpenGames.Preprocessor.CompileSyntax
    - OpenGames.Preprocessor.Parser
    - OpenGames.Preprocessor.RuntimeAST

dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
    - haskeline
    - hashmap
    - hashable
    - extra
    - fgl
    - graphviz
    - lens
    - typed-process
    - mwc-random
    - random
    - vector
    - criterion
    - open-games-hs-engine
