/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package open-games-hs-0.1.0.0 */
#ifndef VERSION_open_games_hs
#define VERSION_open_games_hs "0.1.0.0"
#endif /* VERSION_open_games_hs */
#ifndef MIN_VERSION_open_games_hs
#define MIN_VERSION_open_games_hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_open_games_hs */
/* package QuickCheck-2.14.2 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.14.2"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 2)
#endif /* MIN_VERSION_QuickCheck */
/* package ad-4.5.4 */
#ifndef VERSION_ad
#define VERSION_ad "4.5.4"
#endif /* VERSION_ad */
#ifndef MIN_VERSION_ad
#define MIN_VERSION_ad(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  5 || \
  (major1) == 4 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_ad */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package comonad-5.0.8 */
#ifndef VERSION_comonad
#define VERSION_comonad "5.0.8"
#endif /* VERSION_comonad */
#ifndef MIN_VERSION_comonad
#define MIN_VERSION_comonad(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  0 || \
  (major1) == 5 && (major2) == 0 && (minor) <= 8)
#endif /* MIN_VERSION_comonad */
/* package criterion-1.5.13.0 */
#ifndef VERSION_criterion
#define VERSION_criterion "1.5.13.0"
#endif /* VERSION_criterion */
#ifndef MIN_VERSION_criterion
#define MIN_VERSION_criterion(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 13)
#endif /* MIN_VERSION_criterion */
/* package extra-1.7.13 */
#ifndef VERSION_extra
#define VERSION_extra "1.7.13"
#endif /* VERSION_extra */
#ifndef MIN_VERSION_extra
#define MIN_VERSION_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 13)
#endif /* MIN_VERSION_extra */
/* package fgl-5.7.0.3 */
#ifndef VERSION_fgl
#define VERSION_fgl "5.7.0.3"
#endif /* VERSION_fgl */
#ifndef MIN_VERSION_fgl
#define MIN_VERSION_fgl(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  7 || \
  (major1) == 5 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_fgl */
/* package graphviz-2999.20.1.0 */
#ifndef VERSION_graphviz
#define VERSION_graphviz "2999.20.1.0"
#endif /* VERSION_graphviz */
#ifndef MIN_VERSION_graphviz
#define MIN_VERSION_graphviz(major1,major2,minor) (\
  (major1) <  2999 || \
  (major1) == 2999 && (major2) <  20 || \
  (major1) == 2999 && (major2) == 20 && (minor) <= 1)
#endif /* MIN_VERSION_graphviz */
/* package hashable-1.4.2.0 */
#ifndef VERSION_hashable
#define VERSION_hashable "1.4.2.0"
#endif /* VERSION_hashable */
#ifndef MIN_VERSION_hashable
#define MIN_VERSION_hashable(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_hashable */
/* package hashmap-1.3.3 */
#ifndef VERSION_hashmap
#define VERSION_hashmap "1.3.3"
#endif /* VERSION_hashmap */
#ifndef MIN_VERSION_hashmap
#define MIN_VERSION_hashmap(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_hashmap */
/* package haskeline-0.8.2.1 */
#ifndef VERSION_haskeline
#define VERSION_haskeline "0.8.2.1"
#endif /* VERSION_haskeline */
#ifndef MIN_VERSION_haskeline
#define MIN_VERSION_haskeline(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_haskeline */
/* package lens-5.1.1 */
#ifndef VERSION_lens
#define VERSION_lens "5.1.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  1 || \
  (major1) == 5 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_lens */
/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */
/* package mwc-random-0.15.0.2 */
#ifndef VERSION_mwc_random
#define VERSION_mwc_random "0.15.0.2"
#endif /* VERSION_mwc_random */
#ifndef MIN_VERSION_mwc_random
#define MIN_VERSION_mwc_random(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_mwc_random */
/* package parsec-3.1.15.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.15.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 15)
#endif /* MIN_VERSION_parsec */
/* package poly-0.5.1.0 */
#ifndef VERSION_poly
#define VERSION_poly "0.5.1.0"
#endif /* VERSION_poly */
#ifndef MIN_VERSION_poly
#define MIN_VERSION_poly(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_poly */
/* package probability-0.2.8 */
#ifndef VERSION_probability
#define VERSION_probability "0.2.8"
#endif /* VERSION_probability */
#ifndef MIN_VERSION_probability
#define MIN_VERSION_probability(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 8)
#endif /* MIN_VERSION_probability */
/* package profunctors-5.6.2 */
#ifndef VERSION_profunctors
#define VERSION_profunctors "5.6.2"
#endif /* VERSION_profunctors */
#ifndef MIN_VERSION_profunctors
#define MIN_VERSION_profunctors(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  6 || \
  (major1) == 5 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_profunctors */
/* package random-1.2.1.1 */
#ifndef VERSION_random
#define VERSION_random "1.2.1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_random */
/* package template-haskell-2.18.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.18.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */
/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */
/* package typed-process-0.2.11.0 */
#ifndef VERSION_typed_process
#define VERSION_typed_process "0.2.11.0"
#endif /* VERSION_typed_process */
#ifndef MIN_VERSION_typed_process
#define MIN_VERSION_typed_process(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 11)
#endif /* MIN_VERSION_typed_process */
/* package vector-0.12.3.1 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.3.1"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_vector */

/* tool cpphs-1.20.9 */
#ifndef TOOL_VERSION_cpphs
#define TOOL_VERSION_cpphs "1.20.9"
#endif /* TOOL_VERSION_cpphs */
#ifndef MIN_TOOL_VERSION_cpphs
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_cpphs */
/* tool gcc-11.1.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.1.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  1 || \
  (major1) == 11 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool runghc-9.2.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "open-games-hs-0.1.0.0-3Wb5V87CJHEAShKfD4Vcps"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "open-games-hs-0.1.0.0-3Wb5V87CJHEAShKfD4Vcps"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
