name: open-games-hs-modelling
version: '0.1.0.0'
synopsis: User-facing library for the open-games-hs engine
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.m.zahn@gmail.com
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: MIT
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
    - OpenGames.BayesianModelling.AtomicGames
    - OpenGames.BayesianModelling.Diagnostics
    - OpenGames.MonteCarloModelling.Diagnostics

dependencies:
    - base >=4.7 && <5
    - mtl 
    - open-games-hs-engine
    - open-games-hs-preprocessor
